### PR TITLE
update to 8.0.0, bump runtime and dependencies

### PR DESCRIPTION
**Pull request by renner0e**
Hey all,

I updated the dependencies and runtime and also included the changes from #25 #24 

I'm not a developer. This is how I did it in case I did it wrong.

```
git clone --depth 1 --branch 7.0.0 https://github.com/qarmin/czkawka

git clone https://github.com/flathub/com.github.qarmin.czkawka

cd czkawka/misc/

[enter arch linux container/toolbox]

sudo pacman -S python-aiohttp python-toml

wget https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/master/cargo/flatpak-cargo-generator.py

mkdir -p flatpak

python3 flatpak-cargo-generator.py ../Cargo.lock -o flatpak/cargo-sources.json

cp flatpak/cargo-sources.json ../../com.github.qarmin.czkawka

rm flatpak-cargo-generator.py
```

Building takes an awful lot longer than the previous version

Screenshot_20240430_164100

### CODE REVIEW

**Comment by azzamsa** [comment]
@qarmin hi, sorry for the ping. Would you like to take a look at this?

**Comment by qarmin** [comment]
Hi, I looked at this in https://github.com/flathub/com.github.qarmin.czkawka/pull/24, but errors are quite hard to me to fix them and I don't have time or inclination to delve into the documetation of the flathub

There are now few PRs, but none of them passes CI which is required to merge and release new version.
Perhaps someone will fix them, but there hasn't been much success in six months

**Comment by renner0e** [comment]
bot, build

**Comment by renner0e** [comment]
> Hi, I looked at this in #24, but errors are quite hard to me to fix them and I don't have time or inclination to delve into the documetation of the flathub
> 
> There are now few PRs, but none of them passes CI which is required to merge and release new version. Perhaps someone will fix them, but there hasn't been much success in six months

@qarmin
please take a look at my other PR on the upstream repo at https://github.com/qarmin/czkawka/pull/1275

I could compile it on my machine and run the flatpak from master branch.
appstreamcli has small complaints about the trailing dot in the summary description thing.

As far as I understand you'd have to either tag (just for flathub) a new release after my PR is merged or use the latest commit hash from master branch (from my PR) in the flatpak manifest which will not affect other versions.

The flatpak CI is failing because the version of the anyhow package is outdated(?) and this should be fixed by merging my PR.

Again, I am not a developer I don't know what I'm doing.

**Comment by renner0e** [comment]
oops, I accidentally commited my fork of the repo in the flatpak manifest.

**Comment by qarmin** [comment]
Thanks looks like it's working

However, it's too late for version 7.0.0 because I would have to play with tags in git in the czkawka repo and release version 7.0.1 but a new version will come out soon so it will be easier to just wait and modify PR

> Again, I am not a developer I don't know what I'm doing.

I either often don't know what I'm doing.
But the most important thing is the result, and it looks like there is no probem with that here

**Comment by azzamsa** [comment]
@qarmin Rafał, Thank you so much for Czkawka!

**Comment by renner0e** [comment]
> However, it's too late for version 7.0.0 because I would have to play with tags in git in the czkawka repo and release version 7.0.1 but a new version will come out soon so it will be easier to just wait and modify PR

That's fine if the next release works for flathub.

**Comment by qarmin** [comment]
Thanks

**Pull request merged**
