### PR TITLE
5.0 update

### PR DESCRIPTION
**Pull request by qarmin**

### CODE REVIEW

**Comment by qarmin** [comment]
bot, build

**Comment by TheEvilSkeleton** [comment]
> Started [test build 102766](https://buildbot.flathub.org/#/builders/32/builds/102766)

You should stop this build so someone else can use it instead.

**Comment by qarmin** [comment]
How?
Flathub bot, like a lot other things is not so very well documented

**Comment by qarmin** [comment]
bot, stop

**Comment by qarmin** [comment]
bot, cancel

**Comment by TheEvilSkeleton** [comment]
You press the "Stop" button at the top right https://buildbot.flathub.org/#/builders/32/builds/102766.

**Comment by TheEvilSkeleton** [comment]
Oh...  I meant to say to cancel [102766](https://buildbot.flathub.org/#/builders/32/builds/102766) specifically, because you were reserving two build jobs for the same application. I guess you can try rebuilding again? Sorry for being unclear :sweat_smile:.

**Comment by qarmin** [comment]
I updated freedesktop sdk in second build but I canceled it also, because compilation froze in similar place like previous version(tested 21.08 and 22.08beta)

```
Caused by:
  process didn't exit successfully: `/run/build/czkawka_gui/target/release/build/graphene-sys-1d8666e0c489b8ad/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GRAPHENE_GOBJECT_1.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=`"pkg-config" "--libs" "--cflags" "graphene-gobject-1.0" "graphene-gobject-1.0 >= 1.10"` did not exit successfully: exit status: 1
  error: could not find system library 'graphene-gobject-1.0' required by the 'graphene-sys' crate
  --- stderr
  Package graphene-gobject-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `graphene-gobject-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'graphene-gobject-1.0', required by 'virtual:world', not found
  Package 'graphene-gobject-1.0', required by 'virtual:world', not found
```

**Comment by TheEvilSkeleton** [comment]
Unfortunately I'm not proficient with Rust, so I can't be helpful here.

**Comment by axtloss** [comment]
It seems like it's missing [graphene](https://github.com/ebassi/graphene) in the flatpak, try adding it to the flatpak manifest

**Comment by axtloss** [comment]
Adding
```yml
- name: graphene
  buildsystem: meson
  sources:
  - type: archive
    url: https://github.com/ebassi/graphene/archive/refs/tags/1.10.8.tar.gz
    sha256: 922dc109d2dc5dc56617a29bd716c79dd84db31721a8493a13a5f79109a4a4ed
```
as a module fixes that error, but it results in a new error:
Screenshot from 2022-07-29 22-57-31

**Comment by axtloss** [comment]
After following the dependency chain for a bit, it seems like the freedesktop runtime/sdk specified by the manifest don't include gtk4 dependencies needed, it would be possible to add all of those as modules in the manifest, but it would probably be easier to use a different runtime/sdk like the gnome ones (org.gnome.Platform & org.gnome.Sdk)

**Comment by axtloss** [comment]
I got it to build properly by adding all the deps to the modules:
```yml
- name: py3cairo
  buildsystem: simple
  build-commands:
  - python3 setup.py install --prefix=/app --root=/
  sources:
  - type: archive
    url: https://github.com/pygobject/pycairo/releases/download/v1.21.0/pycairo-1.21.0.tar.gz
    sha256: 251907f18a552df938aa3386657ff4b5a4937dde70e11aa042bc297957f4b74b
- name: python3-gi
  buildsystem: simple
  build-commands:
  - python3 setup.py install --prefix=/app --root=/
  sources:
  - type: archive
    url: https://github.com/GNOME/pygobject/archive/refs/tags/3.42.2.tar.gz
    sha256: 56e6833f875bfe55409c780b9c87a9fc426c1cd55b3c65836de9d384d206201f
- name: graphene
  buildsystem: meson
  sources:
  - type: archive
    url: https://github.com/ebassi/graphene/archive/refs/tags/1.10.8.tar.gz
    sha256: 922dc109d2dc5dc56617a29bd716c79dd84db31721a8493a13a5f79109a4a4ed
- name: gtk4
  buildsystem: meson
  sources:
  - type: archive
    url: https://download.gnome.org/sources/gtk/4.7/gtk-4.7.1.tar.xz
    sha256: dbe0495d2933c461515bfed886b57f4d10b4e70a0c7ce6c933d8720b400d09b4
```

**Pull request merged**
